version: "3.7"
services:

  server:
    container_name: server
    build:
      context: ./server
    command: node index.js
    ports:
      - '3001:3001'

  client:
    container_name: client
    build:
      context: ./client
    command: npm start
    ports:
      - '3000:3000'